# Dependencies
markdown:         redcarpet
# highlighter:         true

# Permalinks
permalink:        pretty

# Setup
url:              http://portlandcodeschool.github.io/jse
baseurl:          /jse

title:            'PCS'
tagline:          'JS Evening'
description:      'JavaScript Evening'
timezone:         GMT
sass: 
  sass_dir:         _sass
author1:
  name:           'Dan Bauer'
  url:            'https://github.com/dsbauer'
author2:
  name:           'Benjamin Verble'
  url:            'https://github.com/BenjaminVerble'


# Custom vars
version:          0.0.1